apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiper
  namespace: irminsul
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/irminsul-dev-wiper
automountServiceAccountToken: false
